theme: jekyll-theme-dinky
title: [Guías Chapter]
descriptio: [Guías de gobierno para un Chapter.]

url: https://rulasg.github.io/guiaschapter"
baseurl: "/guiaschapter"

collections:
  borradores:
    output: true
  guias:
    output: true
